PREGUNTA OBJETIVO: ¿Cómo logró el Leicester City ganar la Premier League 2015/16 contra todos los pronósticos?

CARGAMOS EL DATASET

In [5]:
import pandas as pd

df = pd.read_csv("../data/data/season-1516_csv.csv")

df.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E0,08/08/15,Bournemouth,Aston Villa,0,1,A,0,0,D,...,1.79,26,-0.5,1.98,1.93,1.99,1.92,1.82,3.88,4.70
1,E0,08/08/15,Chelsea,Swansea,2,2,D,2,1,H,...,1.99,27,-1.5,2.24,2.16,1.80,1.73,1.37,5.04,10.88
2,E0,08/08/15,Everton,Watford,2,2,D,0,1,A,...,1.96,26,-1.0,2.28,2.18,1.76,1.71,1.75,3.76,5.44
3,E0,08/08/15,Leicester,Sunderland,4,2,H,3,0,H,...,1.67,26,-0.5,2.00,1.95,1.96,1.90,1.79,3.74,5.10
4,E0,08/08/15,Man United,Tottenham,1,0,H,1,0,H,...,2.01,26,-1.0,2.20,2.09,1.82,1.78,1.64,4.07,6.04

LIMPIAMOS Y RENOMBRAMOS

In [ ]:
columnas = {
    "Div": "division",
    "Date": "match_date",
    "HomeTeam": "home_team",
    "AwayTeam": "away_team",
    "FTHG": "home_goals",
    "FTAG": "away_goals",
    "FTR": "full_time_result",
    "HTHG": "home_half_time_goals",
    "HTAG": "away_half_time_goals",
    "HTR": "half_time_result",
    "Referee": "referee",
    "HS": "home_shots",
    "AS": "away_shots",
    "HST": "home_shots_on_target",
    "AST": "away_shots_on_target",
    "HF": "home_fouls",
    "AF": "away_fouls",
    "HC": "home_corners",
    "AC": "away_corners",
    "HY": "home_yellow_cards",
    "AY": "away_yellow_cards",
    "HR": "home_red_cards",
    "AR": "away_red_cards"
}

df = df.rename(columns=columnas)

df_analysis = df[
    [
        "match_date",
        "home_team",
        "away_team",
        "home_goals",
        "away_goals",
        "full_time_result",
        "home_shots",
        "away_shots",
        "home_shots_on_target",
        "away_shots_on_target",
        "home_corners",
        "away_corners",
        "home_yellow_cards",
        "away_yellow_cards"
    ]
]

CREAMOS EL DATASET QUE NOS IMPORTA

In [22]:
leicester = df_analysis[
    (df_analysis["home_team"] == "Leicester") |
    (df_analysis["away_team"] == "Leicester")
].copy()

leicester.head()

,match_date,home_team,away_team,home_goals,away_goals,full_time_result,home_shots,away_shots,home_shots_on_target,away_shots_on_target,home_corners,away_corners,home_yellow_cards,away_yellow_cards
3,08/08/15,Leicester,Sunderland,4,2,H,19,10,8,5,6,3,2,4
16,15/08/15,West Ham,Leicester,1,2,A,10,11,3,6,8,4,1,3
21,22/08/15,Leicester,Tottenham,1,1,D,13,19,2,6,2,7,1,4
31,29/08/15,Bournemouth,Leicester,1,1,D,5,4,2,2,4,4,2,4
47,13/09/15,Leicester,Aston Villa,3,2,H,21,11,6,4,4,5,2,1

CALCULAMOS VICTORIAS, EMPATES Y DERROTAS

In [ ]:
def leicester_result(row):
    if row["home_team"] == "Leicester":
        if row["full_time_result"] == "H":
            return "Win"
        elif row["full_time_result"] == "D":
            return "Draw"
        else:
            return "Loss"
    else:
        if row["full_time_result"] == "A":
            return "Win"
        elif row["full_time_result"] == "D":
            return "Draw"
        else:
            return "Loss"

leicester["result"] = leicester.apply(leicester_result, axis=1)
leicester["result"].value_counts()


def calcular_puntos_partido(row):
    if row["result"] == "Win":
        return 3
    elif row["result"] == "Draw":
        return 1
    else:
        return 0
    
leicester["points"] = leicester.apply(calcular_puntos_partido, axis=1)
puntos_totales = leicester["points"].sum()

print("Puntos Totales de Leicester:", puntos_totales)

Puntos Totales de Leicester: 81

GOLES A FAVOR Y EN CONTRA

In [26]:
def calcular_goles_favor(row):
    if row["home_team"] == "Leicester":
        return row["home_goals"]
    else:
        return row["away_goals"]

def calcular_goles_contra(row):
    if row["home_team"] == "Leicester":
        return row["away_goals"]
    else:
        return row["home_goals"]

leicester["goals_for"] = leicester.apply(calcular_goles_favor, axis=1)
leicester["goals_against"] = leicester.apply(calcular_goles_contra, axis=1)

print("Goals For:", leicester["goals_for"].sum())
print("Goals Against:", leicester["goals_against"].sum())

Goals For: 68
Goals Against: 36

PRIMERAS CONCLUSIONES

In [27]:
wins = (leicester["result"] == "Win").sum()
draws = (leicester["result"] == "Draw").sum()
losses = (leicester["result"] == "Loss").sum()

print(f"Wins: {wins}")
print(f"Draws: {draws}")
print(f"Losses: {losses}")
print("Goals For:", leicester["goals_for"].sum())
print("Goals Against:", leicester["goals_against"].sum())

Wins: 23
Draws: 12
Losses: 3
Goals For: 68
Goals Against: 36